deploy:
  stage: deploy
  needs:
    - job: build
  artifacts: true
  script:
    - echo "Phase de déploiement"
    - mkdir -p ~/.aws
    - echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\naws_session_token=$AWS_SESSION_TOKEN" > ~/.aws/credentials
    - echo -e "[default]\nregion=$AWS_DEFAULT_REGION" > ~/.aws/config
    - apt update -y && apt install unzip -y
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - S3_BUCKET=$(aws s3 ls | head -n 1 | awk '{print $3}')
    - echo "Uploading artifact to S3 bucket: $S3_BUCKET"
    - aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://$S3_BUCKET/
    - aws elasticbeanstalk create-application-version \
        --application-name mon-app \
        --version-label commit-$CI_COMMIT_SHORT_SHA \
        --source-bundle S3Bucket="$S3_BUCKET",S3Key="demo-0.0.1-SNAPSHOT.jar"
    - aws elasticbeanstalk update-environment \
        --environment-name Springboot-exercices-env \
        --version-label commit-$CI_COMMIT_SHORT_SHA
